version: '3.8'

services: 
    app:
        build: 
            context: .
        restart: always
        ports:
            - "3000:3000"
        container_name: app
        env_file:
            - .env
        depends_on: 
            - db
        volumes:
            - ./src/:/app/src/
    db:
        image: "postgres"
        volumes:
            - data-db:/var/lib/postgresql/data/
        ports: 
            - "5432:5432"
        env_file:
            - .env
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
volumes:
    data-db: